// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/bobot-penilaian" | "/admin/data-pelajaran" | "/admin/guru" | "/admin/kelas" | "/admin/pelajaran" | "/admin/profile" | "/admin/siswa" | "/admin/tahun-ajaran" | "/guru" | "/guru-kelas" | "/guru-kelas/nilai" | "/guru-kelas/presensi" | "/guru-kelas/profile" | "/guru-kelas/quran" | "/guru-mapel" | "/guru-mapel/nilai" | "/guru-mapel/nilai-harian" | "/guru-mapel/nilai-harian-quiz" | "/guru-mapel/presensi" | "/guru-mapel/profile" | "/guru-mapel/quran" | "/guru-mapel/rekap-absensi" | "/guru-mapel/rekap-nilai-akhir" | "/guru/monitoring-presensi" | "/guru/nilai" | "/guru/nilai-harian" | "/guru/nilai-harian-quiz" | "/guru/presensi" | "/guru/profile" | "/guru/quran" | "/guru/rekap-absensi" | "/guru/rekap-nilai" | "/guru/rekap-nilai-akhir" | "/guru/riwayat-quran" | "/login" | "/siswa" | "/siswa/nilai" | "/siswa/presensi" | "/siswa/profile" | "/siswa/quran"
type AppRouteHandlerRoutes = "/api/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/guru" | "/guru-kelas" | "/guru-mapel" | "/siswa"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/bobot-penilaian": {}
  "/admin/data-pelajaran": {}
  "/admin/guru": {}
  "/admin/kelas": {}
  "/admin/pelajaran": {}
  "/admin/profile": {}
  "/admin/siswa": {}
  "/admin/tahun-ajaran": {}
  "/api/[...path]": { "path": string[]; }
  "/guru": {}
  "/guru-kelas": {}
  "/guru-kelas/nilai": {}
  "/guru-kelas/presensi": {}
  "/guru-kelas/profile": {}
  "/guru-kelas/quran": {}
  "/guru-mapel": {}
  "/guru-mapel/nilai": {}
  "/guru-mapel/nilai-harian": {}
  "/guru-mapel/nilai-harian-quiz": {}
  "/guru-mapel/presensi": {}
  "/guru-mapel/profile": {}
  "/guru-mapel/quran": {}
  "/guru-mapel/rekap-absensi": {}
  "/guru-mapel/rekap-nilai-akhir": {}
  "/guru/monitoring-presensi": {}
  "/guru/nilai": {}
  "/guru/nilai-harian": {}
  "/guru/nilai-harian-quiz": {}
  "/guru/presensi": {}
  "/guru/profile": {}
  "/guru/quran": {}
  "/guru/rekap-absensi": {}
  "/guru/rekap-nilai": {}
  "/guru/rekap-nilai-akhir": {}
  "/guru/riwayat-quran": {}
  "/login": {}
  "/siswa": {}
  "/siswa/nilai": {}
  "/siswa/presensi": {}
  "/siswa/profile": {}
  "/siswa/quran": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/guru": never
  "/guru-kelas": never
  "/guru-mapel": never
  "/siswa": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
