// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/bobot-penilaian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bobot-penilaian">> = Specific
  const handler = {} as typeof import("../../src/app/admin/bobot-penilaian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/data-pelajaran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data-pelajaran">> = Specific
  const handler = {} as typeof import("../../src/app/admin/data-pelajaran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/guru/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guru">> = Specific
  const handler = {} as typeof import("../../src/app/admin/guru/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/kelas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kelas">> = Specific
  const handler = {} as typeof import("../../src/app/admin/kelas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pelajaran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pelajaran">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pelajaran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/siswa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/siswa">> = Specific
  const handler = {} as typeof import("../../src/app/admin/siswa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tahun-ajaran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tahun-ajaran">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tahun-ajaran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/nilai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-kelas/nilai">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/nilai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-kelas">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-kelas/presensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-kelas/profile">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/quran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-kelas/quran">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/quran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/nilai-harian-quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/nilai-harian-quiz">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/nilai-harian-quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/nilai-harian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/nilai-harian">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/nilai-harian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/nilai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/nilai">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/nilai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/presensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/profile">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/quran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/quran">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/quran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/rekap-absensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/rekap-absensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/rekap-absensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/rekap-nilai-akhir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru-mapel/rekap-nilai-akhir">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/rekap-nilai-akhir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/monitoring-presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/monitoring-presensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru/monitoring-presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/nilai-harian-quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/nilai-harian-quiz">> = Specific
  const handler = {} as typeof import("../../src/app/guru/nilai-harian-quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/nilai-harian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/nilai-harian">> = Specific
  const handler = {} as typeof import("../../src/app/guru/nilai-harian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/nilai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/nilai">> = Specific
  const handler = {} as typeof import("../../src/app/guru/nilai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru">> = Specific
  const handler = {} as typeof import("../../src/app/guru/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/presensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/profile">> = Specific
  const handler = {} as typeof import("../../src/app/guru/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/quran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/quran">> = Specific
  const handler = {} as typeof import("../../src/app/guru/quran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/rekap-absensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/rekap-absensi">> = Specific
  const handler = {} as typeof import("../../src/app/guru/rekap-absensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/rekap-nilai-akhir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/rekap-nilai-akhir">> = Specific
  const handler = {} as typeof import("../../src/app/guru/rekap-nilai-akhir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/rekap-nilai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/rekap-nilai">> = Specific
  const handler = {} as typeof import("../../src/app/guru/rekap-nilai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/riwayat-quran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guru/riwayat-quran">> = Specific
  const handler = {} as typeof import("../../src/app/guru/riwayat-quran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/nilai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siswa/nilai">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/nilai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siswa">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/presensi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siswa/presensi">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/presensi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siswa/profile">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/quran/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siswa/quran">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/quran/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-kelas/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/guru-kelas">> = Specific
  const handler = {} as typeof import("../../src/app/guru-kelas/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru-mapel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/guru-mapel">> = Specific
  const handler = {} as typeof import("../../src/app/guru-mapel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guru/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/guru">> = Specific
  const handler = {} as typeof import("../../src/app/guru/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siswa/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/siswa">> = Specific
  const handler = {} as typeof import("../../src/app/siswa/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
